### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by silu44** [ionicthemes/ionic3-wordpress-integration#19]
after npm install 

Error: Cannot find module '@angular/tsc-wrapped/src/tsc'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:~~~\wordpress\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:7:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by silu44** [comment]
Slove 

npm install npm@latest -g
npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest
npm install @angular/tsc-wrapped autoprefixer

**Comment by djabif** [comment]
Thanks for the update
